/**
 * ParentsPage.jsx
 * Parents management page for the School Admin role.
 * Provides CRUD for parent accounts: add/edit, deactivate/
 * reactivate, and password reset to default.
 * Key behaviour: passwords are auto-generated by the backend
 * (schoolCode + last 4 digits of phone). Admin must share the
 * default_password shown after create/reset with the parent.
 * Page title rendered by Topbar — no page-level h1.
 */
import { useState, useEffect, useRef, useCallback } from 'react';
import {
  Plus, Pencil, Power, PowerOff, KeyRound, Users,
  X, Search, Loader2, Copy, Check,
} from 'lucide-react';
import {
  listParents, createParent, updateParent,
  deactivateParent, reactivateParent, resetParentPassword,
} from '../../api/users.api';
import { cn } from '../../lib/utils';

/* ──────────────────────────────────────────────────────────
 * Constants
 * ────────────────────────────────────────────────────────── */

const PAGE_LIMIT = 20;
const DEBOUNCE_MS = 400;

/* ──────────────────────────────────────────────────────────
 * Utility helpers
 * ────────────────────────────────────────────────────────── */

// Returns condensed page list with ellipsis for gaps
function getVisiblePages(current, total) {
  if (total <= 7) return Array.from({ length: total }, (_, i) => i + 1);

  const pages = new Set();
  pages.add(1);
  pages.add(total);
  for (let i = Math.max(2, current - 2); i <= Math.min(total - 1, current + 2); i++) {
    pages.add(i);
  }

  const sorted = [...pages].sort((a, b) => a - b);
  const result = [];
  for (let i = 0; i < sorted.length; i++) {
    if (i > 0 && sorted[i] - sorted[i - 1] > 1) result.push('...');
    result.push(sorted[i]);
  }
  return result;
}

// Formats ISO timestamp as DD Mon YYYY. Returns "Never" if null.
function fmtDate(iso) {
  if (!iso) return 'Never';
  const d = new Date(iso);
  const months = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ];
  const day = String(d.getDate()).padStart(2, '0');
  const mon = months[d.getMonth()];
  const yr = d.getFullYear();
  return `${day} ${mon} ${yr}`;
}

/* ──────────────────────────────────────────────────────────
 * Reusable Modal shell
 * ────────────────────────────────────────────────────────── */

/**
 * Renders a backdrop + centred card. Closes on Escape and
 * backdrop click. Traps Tab focus within the dialog.
 */
function Modal({ open, onClose, title, disableClose = false, children }) {
  const dialogRef = useRef(null);

  // Close on Escape key
  useEffect(() => {
    if (!open) return;
    function onKey(e) {
      if (e.key === 'Escape' && !disableClose) onClose();
    }
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, onClose, disableClose]);

  // Focus trap — save previous focus, constrain Tab, restore on close
  useEffect(() => {
    if (!open) return;
    const previouslyFocused = document.activeElement;

    function getFocusable() {
      const candidates = dialogRef.current?.querySelectorAll(
        'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
      );
      if (!candidates) return [];
      return Array.from(candidates).filter((el) => {
        if (el.disabled) return false;
        if (el.hidden) return false;
        if (el.getAttribute('aria-hidden') === 'true') return false;
        if (!el.offsetParent && el.tagName !== 'BODY') return false;
        return true;
      });
    }

    // Re-query live focusable elements on each Tab press
    function handleTab(e) {
      if (e.key !== 'Tab') return;
      const current = getFocusable();
      if (!current.length) return;
      const first = current[0];
      const last = current[current.length - 1];
      if (e.shiftKey) {
        if (document.activeElement === first) { e.preventDefault(); last.focus(); }
      } else {
        if (document.activeElement === last) { e.preventDefault(); first.focus(); }
      }
    }

    const focusable = getFocusable();
    if (focusable.length) focusable[0].focus();
    else dialogRef.current?.focus();

    document.addEventListener('keydown', handleTab);
    return () => {
      document.removeEventListener('keydown', handleTab);
      if (previouslyFocused?.focus) previouslyFocused.focus();
    };
  }, [open]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50"
        onClick={disableClose ? undefined : onClose}
        aria-hidden="true"
      />
      {/* Card */}
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-label={title}
        tabIndex={-1}
        className="relative z-10 mx-4 w-full max-w-md rounded-xl border border-slate-200 bg-white p-6 shadow-xl md:mx-0"
      >
        {/* Header */}
        <div className="mb-4 flex items-center justify-between">
          <h2 className="text-lg font-semibold text-slate-800">{title}</h2>
          <button
            type="button"
            onClick={onClose}
            disabled={disableClose}
            className="rounded-md p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-300 disabled:opacity-40 disabled:cursor-not-allowed"
            aria-label="Close"
          >
            <X className="h-5 w-5" />
          </button>
        </div>
        {children}
      </div>
    </div>
  );
}

/* ──────────────────────────────────────────────────────────
 * Default Password Banner
 * ────────────────────────────────────────────────────────── */

/**
 * One-time banner shown after create or password reset.
 * Displays the auto-generated password for the admin to share.
 */
function DefaultPasswordBanner({ password, onDismiss }) {
  const [copied, setCopied] = useState(false);

  // Only show Copied! when clipboard write actually succeeded
  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(password);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard denied — password visible for manual copy
      setCopied(false);
    }
  }

  return (
    <div className="rounded-xl border border-amber-200 bg-amber-50 p-4">
      <div className="flex items-center gap-2">
        <span className="text-lg" aria-hidden="true">⚠️</span>
        <p className="font-semibold text-amber-800">
          Share this password with the parent
        </p>
      </div>
      <p className="mt-1 text-sm text-amber-700">
        This password is auto-generated and shown only once.
        The parent uses it to log in to the mobile app.
      </p>

      {/* Password display */}
      <div className="mt-3 flex flex-col gap-2 sm:flex-row sm:items-center">
        <span className="flex-1 select-all rounded-lg border border-amber-200 bg-white px-3 py-2 font-mono text-sm text-slate-800">
          {password}
        </span>
        <button
          type="button"
          onClick={handleCopy}
          aria-label="Copy password to clipboard"
          className={cn(
            'inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-amber-300',
            copied
              ? 'bg-green-100 text-green-700'
              : 'bg-white border border-amber-200 text-amber-700 hover:bg-amber-100'
          )}
        >
          {copied ? (
            <>
              <Check className="h-4 w-4" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="h-4 w-4" />
              Copy
            </>
          )}
        </button>
      </div>

      {/* Dismiss */}
      <button
        type="button"
        onClick={onDismiss}
        className="mt-3 w-full rounded-lg bg-amber-600 px-4 py-2 text-sm font-medium text-white hover:bg-amber-700 focus:outline-none focus:ring-2 focus:ring-amber-500"
      >
        Done — I have shared the password
      </button>
    </div>
  );
}

/* ──────────────────────────────────────────────────────────
 * Parent Add / Edit modal
 * ────────────────────────────────────────────────────────── */

/**
 * Modal form for creating or editing a parent account.
 * After successful create the auto-generated password is shown
 * via DefaultPasswordBanner before closing.
 */
function ParentModal({ modal, onClose, onPasswordReceived }) {
  const isEdit = modal.mode === 'edit';
  const [name, setName] = useState('');
  const [phone, setPhone] = useState('');
  const [email, setEmail] = useState('');
  const [saving, setSaving] = useState(false);
  const [formError, setFormError] = useState(null);
  const [newDefaultPassword, setNewDefaultPassword] = useState(null);

  // Populate or clear fields when the modal opens
  useEffect(() => {
    if (!modal.open) {
      setNewDefaultPassword(null);
      return;
    }
    if (isEdit && modal.parent) {
      setName(modal.parent.name || '');
      setPhone(modal.parent.phone || '');
      setEmail(modal.parent.email || '');
    } else {
      setName('');
      setPhone('');
      setEmail('');
    }
    setFormError(null);
    setNewDefaultPassword(null);
  }, [modal.open, modal.mode, modal.parent]);

  /** Validates and submits the parent form. */
  async function handleSubmit(e) {
    e.preventDefault();
    setFormError(null);

    const trimmedName = name.trim();
    if (!trimmedName) {
      setFormError('Name is required.');
      return;
    }
    if (!phone.trim()) {
      setFormError('Phone is required.');
      return;
    }

    let payload;
    if (isEdit) {
      // Only send changed fields
      const changes = {};
      if (trimmedName !== modal.parent.name) changes.name = trimmedName;
      if (phone.trim() !== (modal.parent.phone || '')) changes.phone = phone.trim();
      if (email.trim() !== (modal.parent.email || '')) changes.email = email.trim() || undefined;

      if (Object.keys(changes).length === 0) {
        onClose();
        return;
      }
      payload = changes;
    } else {
      payload = {
        name: trimmedName,
        phone: phone.trim(),
        email: email.trim() || undefined,
      };
    }

    setSaving(true);
    try {
      if (isEdit) {
        await updateParent(modal.parent.id, payload);
        onClose();
      } else {
        const result = await createParent(payload);
        // Show the auto-generated password before closing
        setNewDefaultPassword(result.default_password);
      }
    } catch (err) {
      setFormError(err.response?.data?.message || 'Failed to save parent');
    } finally {
      setSaving(false);
    }
  }

  /** Dismisses the password banner and triggers list refresh. */
  function handlePasswordDismiss() {
    setNewDefaultPassword(null);
    onPasswordReceived();
    onClose();
  }

  return (
    <Modal
      open={modal.open}
      onClose={onClose}
      title={isEdit ? 'Edit Parent' : 'Add Parent'}
      disableClose={saving || !!newDefaultPassword}
    >
      {newDefaultPassword ? (
        <DefaultPasswordBanner
          password={newDefaultPassword}
          onDismiss={handlePasswordDismiss}
        />
      ) : (
        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Name */}
          <div>
            <label htmlFor="parent-name" className="mb-1 block text-sm font-medium text-slate-700">
              Name <span className="text-red-500">*</span>
            </label>
            <input
              id="parent-name"
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              disabled={saving}
              placeholder="e.g. Priya Sharma"
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-800 placeholder:text-slate-400 focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-300 disabled:opacity-50"
            />
          </div>

          {/* Phone */}
          <div>
            <label htmlFor="parent-phone" className="mb-1 block text-sm font-medium text-slate-700">
              Phone <span className="text-red-500">*</span>
            </label>
            <input
              id="parent-phone"
              type="text"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
              disabled={saving}
              placeholder="e.g. 9876543210"
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-800 placeholder:text-slate-400 focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-300 disabled:opacity-50"
            />
            <p className="mt-1 text-xs text-slate-400">
              Used to generate the default login password
            </p>
          </div>

          {/* Email */}
          <div>
            <label htmlFor="parent-email" className="mb-1 block text-sm font-medium text-slate-700">
              Email
            </label>
            <input
              id="parent-email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              disabled={saving}
              placeholder="e.g. parent@email.com"
              className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-800 placeholder:text-slate-400 focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-300 disabled:opacity-50"
            />
          </div>

          {formError && (
            <p className="text-sm text-red-600">{formError}</p>
          )}

          <div className="flex justify-end gap-2 pt-2">
            <button
              type="button"
              onClick={onClose}
              disabled={saving}
              className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-300 disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving}
              className="inline-flex items-center gap-2 rounded-lg bg-slate-800 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-slate-500 disabled:opacity-50"
            >
              {saving && <Loader2 className="h-4 w-4 animate-spin" />}
              {isEdit ? 'Save Changes' : 'Add Parent'}
            </button>
          </div>
        </form>
      )}
    </Modal>
  );
}

/* ──────────────────────────────────────────────────────────
 * Reset Parent Password modal
 * ────────────────────────────────────────────────────────── */

/**
 * Two-view modal: first confirms the reset, then shows the
 * new default password via DefaultPasswordBanner.
 */
function ResetParentPasswordModal({ modal, onClose }) {
  const [resetting, setResetting] = useState(false);
  const [resetError, setResetError] = useState(null);
  const [resetResult, setResetResult] = useState(null);

  // Clear state when modal opens/closes
  useEffect(() => {
    if (!modal.open) {
      setResetResult(null);
      return;
    }
    setResetting(false);
    setResetError(null);
    setResetResult(null);
  }, [modal.open]);

  /** Calls the reset endpoint and stores the new default password. */
  async function handleReset() {
    setResetting(true);
    setResetError(null);
    try {
      const result = await resetParentPassword(modal.parentId);
      setResetResult(result.default_password);
    } catch (err) {
      setResetError(err.response?.data?.message || 'Failed to reset password');
    } finally {
      setResetting(false);
    }
  }

  return (
    <Modal
      open={modal.open}
      onClose={onClose}
      title="Reset Parent Password"
      disableClose={resetting || !!resetResult}
    >
      {resetResult ? (
        <DefaultPasswordBanner
          password={resetResult}
          onDismiss={onClose}
        />
      ) : (
        <div className="space-y-4">
          <p className="text-sm text-slate-600">
            This will reset <span className="font-medium">{modal.parentName}</span>'s
            password back to the default: school code + last 4 digits of their
            phone number. The parent will need to use this new password to log in.
          </p>

          {resetError && (
            <p className="text-sm text-red-600">{resetError}</p>
          )}

          <div className="flex justify-end gap-2 pt-2">
            <button
              type="button"
              onClick={onClose}
              disabled={resetting}
              className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-300 disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleReset}
              disabled={resetting}
              className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-400 disabled:opacity-50"
            >
              {resetting && <Loader2 className="h-4 w-4 animate-spin" />}
              Reset to Default
            </button>
          </div>
        </div>
      )}
    </Modal>
  );
}

/* ──────────────────────────────────────────────────────────
 * Confirm (Deactivate / Reactivate) modal
 * ────────────────────────────────────────────────────────── */

/** Confirmation dialog for deactivate / reactivate actions. */
function ConfirmModal({ modal, onClose, onConfirm }) {
  const [confirming, setConfirming] = useState(false);
  const [confirmError, setConfirmError] = useState(null);

  // Reset state when modal opens/closes
  useEffect(() => {
    setConfirming(false);
    setConfirmError(null);
  }, [modal.open]);

  const titles = {
    deactivate: 'Confirm Deactivate',
    reactivate: 'Confirm Reactivate',
  };

  /** Executes the confirmed action. */
  async function handleConfirm() {
    setConfirming(true);
    setConfirmError(null);
    try {
      await onConfirm(modal.action, modal.parentId);
      onClose();
    } catch (err) {
      setConfirmError(err.response?.data?.message || 'Action failed');
    } finally {
      setConfirming(false);
    }
  }

  return (
    <Modal
      open={modal.open}
      onClose={onClose}
      title={titles[modal.action] || 'Confirm'}
      disableClose={confirming}
    >
      <div className="space-y-4">
        <p className="text-sm text-slate-600">{modal.label}</p>

        {confirmError && (
          <p className="text-sm text-red-600">{confirmError}</p>
        )}

        <div className="flex justify-end gap-2 pt-2">
          <button
            type="button"
            onClick={onClose}
            disabled={confirming}
            className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-300 disabled:opacity-50"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleConfirm}
            disabled={confirming}
            className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-400 disabled:opacity-50"
          >
            {confirming && <Loader2 className="h-4 w-4 animate-spin" />}
            Confirm
          </button>
        </div>
      </div>
    </Modal>
  );
}

/* ──────────────────────────────────────────────────────────
 * Main component
 * ────────────────────────────────────────────────────────── */

/** Parents management page — CRUD, status toggle, password reset. */
export default function ParentsPage() {
  /* ── Core list state ── */
  const [parents, setParents] = useState([]);
  const [pagination, setPagination] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefetching, setIsRefetching] = useState(false);
  const [error, setError] = useState(null);

  /* ── Search state (inputValue = display, apiSearch = fetch trigger) ── */
  const [inputValue, setInputValue] = useState('');
  const [apiSearch, setApiSearch] = useState('');

  /* ── Filter + pagination state ── */
  const [statusFilter, setStatusFilter] = useState('all');
  const [currentPage, setCurrentPage] = useState(1);

  /* ── Modal state ── */
  const [parentModal, setParentModal] = useState({
    open: false, mode: 'add', parent: null,
  });
  const [resetModal, setResetModal] = useState({
    open: false, parentId: null, parentName: '',
  });
  const [confirmModal, setConfirmModal] = useState({
    open: false, action: null, parentId: null,
    parentName: '', label: '',
  });

  /* ── Refs ── */
  const hasFetchedRef = useRef(false);
  const debounceRef = useRef(null);
  const tableTopRef = useRef(null);

  /* ── Data fetching ── */

  // Fetches parents — accepts an optional signal so callers can cancel
  const fetchParents = useCallback(async (page, search, status, signal) => {
    if (!hasFetchedRef.current) {
      setIsLoading(true);
    } else {
      setIsRefetching(true);
    }
    setError(null);

    try {
      const data = await listParents(
        { page, limit: PAGE_LIMIT, search: search || undefined, status },
        signal
      );
      if (!signal?.aborted) {
        const totalPages = data.pagination?.total_pages || 1;
        if (page > totalPages) setCurrentPage(totalPages);
        setParents(data.parents || []);
        setPagination(data.pagination || null);
        hasFetchedRef.current = true;
      }
    } catch (err) {
      if (err.name === 'CanceledError' || err.name === 'AbortError') return;
      setError(err.response?.data?.message || 'Failed to load parents');
    } finally {
      if (!signal?.aborted) {
        setIsLoading(false);
        setIsRefetching(false);
      }
    }
  }, []);

  // Single fetch trigger — handlers only update state, this effect fetches
  useEffect(() => {
    // Create controller synchronously so cleanup can abort
    // immediately regardless of async function progress
    const controller = new AbortController();
    fetchParents(currentPage, apiSearch, statusFilter, controller.signal);
    return () => controller.abort();
  }, [currentPage, apiSearch, statusFilter, fetchParents]);

  // Cancel pending debounce timer on unmount
  useEffect(() => {
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, []);

  // Direct fetch for post-mutation refresh
  function refetch() {
    fetchParents(currentPage, apiSearch, statusFilter);
  }

  /* ── Search handler ── */

  function handleSearchChange(value) {
    setInputValue(value);
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      setApiSearch(value);
      setCurrentPage(1);
      debounceRef.current = null;
    }, DEBOUNCE_MS);
  }

  /* ── Filter handler ── */

  function handleStatusFilter(status) {
    if (debounceRef.current) {
      clearTimeout(debounceRef.current);
      debounceRef.current = null;
    }
    setStatusFilter(status);
    setCurrentPage(1);
  }

  /* ── Pagination ── */

  function goToPage(page) {
    setCurrentPage(page);
    tableTopRef.current?.scrollIntoView({ behavior: 'smooth' });
  }

  /* ── Modal openers ── */

  function openAddParent() {
    setParentModal({ open: true, mode: 'add', parent: null });
  }

  function openEditParent(parent) {
    setParentModal({ open: true, mode: 'edit', parent });
  }

  function openResetPassword(parent) {
    setResetModal({ open: true, parentId: parent.id, parentName: parent.name });
  }

  function openDeactivate(parent) {
    setConfirmModal({
      open: true,
      action: 'deactivate',
      parentId: parent.id,
      parentName: parent.name,
      label: `Deactivating ${parent.name} will prevent them from logging in to the parent app. Their linked students will not be affected.`,
    });
  }

  function openReactivate(parent) {
    setConfirmModal({
      open: true,
      action: 'reactivate',
      parentId: parent.id,
      parentName: parent.name,
      label: `This will allow ${parent.name} to log in to the parent app again.`,
    });
  }

  /* ── Confirm action handler ── */

  async function handleConfirmAction(action, parentId) {
    if (action === 'deactivate') {
      await deactivateParent(parentId);
    } else if (action === 'reactivate') {
      await reactivateParent(parentId);
    }
    refetch();
  }

  /* ── Parent modal success ── */

  function onParentSuccess() {
    if (currentPage === 1) {
      fetchParents(1, apiSearch, statusFilter);
    } else {
      setCurrentPage(1);
    }
  }

  /* ── Render ── */

  const COL_COUNT = 6;
  const filterBtns = [
    { value: 'all', label: 'All' },
    { value: 'active', label: 'Active' },
    { value: 'inactive', label: 'Inactive' },
  ];

  return (
    <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6" ref={tableTopRef}>

      {/* Header */}
      <div className="mb-6 flex items-center justify-between">
        <p className="text-xl font-semibold text-slate-800">Parents</p>
        <button
          type="button"
          onClick={openAddParent}
          className="inline-flex items-center gap-1.5 rounded-lg bg-slate-800 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-slate-500"
        >
          <Plus className="h-4 w-4" />
          Add Parent
        </button>
      </div>

      {/* Subtle refetch indicator */}
      {isRefetching && (
        <div className="mb-3 flex items-center gap-2 text-xs text-slate-500">
          <Loader2 className="h-3.5 w-3.5 animate-spin" />
          Refreshing...
        </div>
      )}

      {/* Search + filter row */}
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-center">
        <div className="relative min-w-[200px] flex-1">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
          <input
            type="text"
            value={inputValue}
            onChange={(e) => handleSearchChange(e.target.value)}
            placeholder="Search name or phone..."
            aria-label="Search parents by name or phone number"
            className="w-full rounded-lg border border-slate-300 py-2 pl-9 pr-9 text-sm text-slate-800 placeholder:text-slate-400 focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-300"
          />
          {inputValue && (
            <button
              type="button"
              onClick={() => handleSearchChange('')}
              aria-label="Clear search"
              className="absolute right-2.5 top-1/2 -translate-y-1/2 rounded p-0.5 text-slate-400 hover:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-300"
            >
              <X className="h-4 w-4" />
            </button>
          )}
        </div>

        {/* Status filter */}
        <div className="flex overflow-hidden rounded-lg border border-slate-300">
          {filterBtns.map((btn) => (
            <button
              key={btn.value}
              type="button"
              onClick={() => handleStatusFilter(btn.value)}
              className={cn(
                'px-3 py-2 text-sm font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-inset focus:ring-slate-300',
                statusFilter === btn.value
                  ? 'bg-slate-800 text-white'
                  : 'bg-white text-slate-600 hover:bg-slate-50'
              )}
            >
              {btn.label}
            </button>
          ))}
        </div>
      </div>

      {/* Error banner */}
      {error && (
        <div className="mb-4 flex items-center justify-between rounded-lg border border-red-200 bg-red-50 p-4">
          <p className="text-sm text-red-700">{error}</p>
          <button
            type="button"
            onClick={refetch}
            className="ml-4 inline-flex shrink-0 items-center gap-1.5 rounded-md bg-red-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-400"
          >
            Retry
          </button>
        </div>
      )}

      {/* Parents table — hidden on mobile, visible on md+ */}
      <div className="hidden md:block">
        <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white">
          <table className="w-full text-sm">
            <thead className="bg-slate-50 text-left text-slate-600">
              <tr>
                <th className="px-4 py-3 font-medium">Name</th>
                <th className="px-4 py-3 font-medium">Phone</th>
                <th className="px-4 py-3 font-medium">Email</th>
                <th className="px-4 py-3 font-medium">Last Active</th>
                <th className="px-4 py-3 font-medium">Status</th>
                <th className="px-4 py-3 font-medium text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">

              {/* Loading skeleton */}
              {isLoading && Array.from({ length: 6 }).map((_, i) => (
                <tr key={i}>
                  {Array.from({ length: COL_COUNT }).map((__, j) => (
                    <td key={j} className="px-4 py-3">
                      <div className="h-4 w-20 animate-pulse rounded bg-slate-200" />
                    </td>
                  ))}
                </tr>
              ))}

              {/* Empty state */}
              {!isLoading && !error && parents.length === 0 && (
                <tr>
                  <td colSpan={COL_COUNT} className="px-4 py-16 text-center">
                    <div className="flex flex-col items-center">
                      <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-slate-100">
                        <Users className="h-6 w-6 text-slate-400" />
                      </div>
                      <p className="text-sm text-slate-500">No parents found</p>
                    </div>
                  </td>
                </tr>
              )}

              {/* Parent rows */}
              {!isLoading && parents.map((parent) => (
                <tr key={parent.id} className="hover:bg-slate-50">
                  <td className="px-4 py-3 font-medium text-slate-800">
                    {parent.name}
                  </td>
                  <td className="px-4 py-3 text-slate-600">
                    {parent.phone || <span className="text-slate-400">—</span>}
                  </td>
                  <td className="px-4 py-3 text-slate-600">
                    {parent.email || <span className="text-slate-400">—</span>}
                  </td>
                  <td className="px-4 py-3 text-sm text-slate-500">
                    {fmtDate(parent.last_active_at)}
                  </td>
                  <td className="px-4 py-3">
                    <span className={cn(
                      'inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium',
                      parent.is_active
                        ? 'bg-green-100 text-green-700'
                        : 'bg-slate-100 text-slate-500'
                    )}>
                      {parent.is_active ? 'Active' : 'Inactive'}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center justify-end gap-1">
                      <button
                        type="button"
                        onClick={() => openEditParent(parent)}
                        aria-label={`Edit parent ${parent.name}`}
                        className="rounded p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-300"
                      >
                        <Pencil className="h-4 w-4" />
                      </button>
                      <button
                        type="button"
                        onClick={() => openResetPassword(parent)}
                        aria-label={`Reset password for ${parent.name}`}
                        className="rounded p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600 focus:outline-none focus:ring-2 focus:ring-slate-300"
                      >
                        <KeyRound className="h-4 w-4" />
                      </button>
                      {parent.is_active ? (
                        <button
                          type="button"
                          onClick={() => openDeactivate(parent)}
                          aria-label={`Deactivate parent ${parent.name}`}
                          className="rounded p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-600 focus:outline-none focus:ring-2 focus:ring-red-300"
                        >
                          <PowerOff className="h-4 w-4" />
                        </button>
                      ) : (
                        <button
                          type="button"
                          onClick={() => openReactivate(parent)}
                          aria-label={`Reactivate parent ${parent.name}`}
                          className="rounded p-1.5 text-slate-400 hover:bg-green-50 hover:text-green-600 focus:outline-none focus:ring-2 focus:ring-green-300"
                        >
                          <Power className="h-4 w-4" />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}

            </tbody>
          </table>
        </div>
      </div>

      {/* Mobile card list — visible on mobile, hidden on md+ */}
      <div className="md:hidden space-y-3">
        {/* Loading skeleton cards */}
        {isLoading && Array.from({ length: 4 }).map((_, i) => (
          <div key={i} className="animate-pulse space-y-3 rounded-xl border border-slate-200 bg-white p-4">
            <div className="h-4 w-32 rounded bg-slate-200" />
            <div className="h-3 w-24 rounded bg-slate-200" />
            <div className="h-3 w-40 rounded bg-slate-200" />
          </div>
        ))}

        {/* Empty state */}
        {!isLoading && !error && parents.length === 0 && (
          <div className="rounded-xl border border-slate-200 bg-white px-4 py-16 text-center">
            <div className="flex flex-col items-center">
              <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-slate-100">
                <Users className="h-6 w-6 text-slate-400" />
              </div>
              <p className="text-sm text-slate-500">No parents found</p>
            </div>
          </div>
        )}

        {/* Parent cards */}
        {!isLoading && parents.map((parent) => (
          <div key={parent.id} className="rounded-xl border border-slate-200 bg-white p-4">
            {/* Card header: name + status badge */}
            <div className="mb-3 flex items-start justify-between">
              <div>
                <p className="font-medium text-slate-800">{parent.name}</p>
                <p className="mt-0.5 text-xs text-slate-500">
                  {parent.phone || '—'}
                </p>
              </div>
              <span className={cn(
                'inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium',
                parent.is_active
                  ? 'bg-green-100 text-green-700'
                  : 'bg-slate-100 text-slate-500'
              )}>
                {parent.is_active ? 'Active' : 'Inactive'}
              </span>
            </div>

            {/* Card body: contact details */}
            <div className="mb-4 space-y-1">
              <p className="text-sm text-slate-600">
                <span className="text-xs text-slate-400">Email: </span>
                {parent.email || '—'}
              </p>
              <p className="text-sm text-slate-500">
                <span className="text-xs text-slate-400">Last active: </span>
                {fmtDate(parent.last_active_at)}
              </p>
            </div>

            {/* Card footer: action buttons */}
            <div className="flex items-center gap-2 border-t border-slate-100 pt-3">
              <button
                type="button"
                onClick={() => openEditParent(parent)}
                aria-label={`Edit parent ${parent.name}`}
                className="flex-1 inline-flex items-center justify-center gap-1.5 rounded-lg border border-slate-300 px-3 py-2 text-xs font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-300"
              >
                <Pencil className="h-3.5 w-3.5" />
                Edit
              </button>
              <button
                type="button"
                onClick={() => openResetPassword(parent)}
                aria-label={`Reset password for ${parent.name}`}
                className="flex-1 inline-flex items-center justify-center gap-1.5 rounded-lg border border-slate-300 px-3 py-2 text-xs font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-300"
              >
                <KeyRound className="h-3.5 w-3.5" />
                Reset
              </button>
              {parent.is_active ? (
                <button
                  type="button"
                  onClick={() => openDeactivate(parent)}
                  aria-label={`Deactivate parent ${parent.name}`}
                  className="flex-1 inline-flex items-center justify-center gap-1.5 rounded-lg border border-red-200 px-3 py-2 text-xs font-medium text-red-600 hover:bg-red-50 focus:outline-none focus:ring-2 focus:ring-red-300"
                >
                  <PowerOff className="h-3.5 w-3.5" />
                  Deactivate
                </button>
              ) : (
                <button
                  type="button"
                  onClick={() => openReactivate(parent)}
                  aria-label={`Reactivate parent ${parent.name}`}
                  className="flex-1 inline-flex items-center justify-center gap-1.5 rounded-lg border border-green-200 px-3 py-2 text-xs font-medium text-green-600 hover:bg-green-50 focus:outline-none focus:ring-2 focus:ring-green-300"
                >
                  <Power className="h-3.5 w-3.5" />
                  Reactivate
                </button>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Pagination */}
      {pagination && pagination.totalPages > 1 && (
        <div className="mt-4 flex flex-wrap items-center justify-center gap-2">
          <button
            type="button"
            onClick={() => goToPage(currentPage - 1)}
            disabled={currentPage <= 1}
            className="rounded-lg border border-slate-300 px-3 py-1.5 text-sm font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-300 disabled:cursor-not-allowed disabled:opacity-40"
          >
            Previous
          </button>
          {getVisiblePages(currentPage, pagination.totalPages).map((item, idx) =>
            item === '...' ? (
              <span key={`ellipsis-${idx}`} className="select-none px-2 py-1.5 text-sm text-slate-400">
                ...
              </span>
            ) : (
              <button
                key={item}
                type="button"
                onClick={() => goToPage(item)}
                className={cn(
                  'rounded-lg px-3 py-1.5 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-slate-300',
                  item === currentPage
                    ? 'bg-slate-800 text-white'
                    : 'border border-slate-300 text-slate-700 hover:bg-slate-50'
                )}
              >
                {item}
              </button>
            )
          )}
          <button
            type="button"
            onClick={() => goToPage(currentPage + 1)}
            disabled={currentPage >= pagination.totalPages}
            className="rounded-lg border border-slate-300 px-3 py-1.5 text-sm font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-300 disabled:cursor-not-allowed disabled:opacity-40"
          >
            Next
          </button>
        </div>
      )}

      {/* Modals */}
      <ParentModal
        modal={parentModal}
        onClose={() => setParentModal((m) => ({ ...m, open: false }))}
        onPasswordReceived={onParentSuccess}
      />
      <ResetParentPasswordModal
        modal={resetModal}
        onClose={() => setResetModal((m) => ({ ...m, open: false }))}
      />
      <ConfirmModal
        modal={confirmModal}
        onClose={() => setConfirmModal((m) => ({ ...m, open: false }))}
        onConfirm={handleConfirmAction}
      />

    </div>
  );
}
